version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  django:
    build:
      context: .
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost"
      SECRET_KEY: "mysecret"
      DB_HOST: db
      DB_NAME: "demo"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_PORT: "5432"
      DOMAIN: "localhost"
      DOMAIN_URL: "http://localhost"
      STATIC_URL: "/static/"
      MEDIA_URL: "/media/"
    expose:
      - 8000
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379
    depends_on:
      - django


  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./../caddy_data:/data
        - .:/usr/src/app/
    depends_on:
      - django