version: '3.1'

services:

  django:
    build:
      context: .
      dockerfile: ./Dockerfiles/django/Dockerfile
    restart: always
    entrypoint: /django-launcher.dev.sh
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,my-demo.localhost"
      SECRET_KEY: "mysecret"
      DOMAIN: "my-demo.localhost"
      DOMAIN_URL: "http://my-demo.localhost"
      STATIC_URL: "/static/"
      MEDIA_URL: "/media/"
      REDIS_URL: redis
    expose:
      - 8000

  redis:
    image: redis:alpine
    restart: always
    expose:
      - 6379

  caddy:
    image: caddy:alpine
    restart: always
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - ./caddy_data:/data
        - .:/usr/src/app/
    depends_on:
      - django
