# Generated by Django 3.1.7 on 2021-03-12 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20210309_2038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
